window.PROJECTS_DATA = [
    {
        id: 'personal-card',
        title: 'Personal Card',
        difficulty: 'Beginner',
        language: 'HTML/CSS',
        description: 'بطاقة شخصية بسيطة تعرض الاسم، الوصف، والسوشيال ميديا.',
        requirements: ['اسم', 'صورة شخصية', 'زر التواصل'],
        technologies: ['HTML', 'CSS'],
        steps: ['بناء هيكل HTML', 'تطبيق النمط', 'إضافة الأزرار'],
        challenge: 'أضف خلفية متدرجة وتأثير hover على الزر.',
        bonus: 'أضف animation خفيف عند فتح البطاقة.',
        status: 'Not Started'
    },
    {
        id: 'simple-profile',
        title: 'Simple Profile',
        difficulty: 'Beginner',
        language: 'HTML/CSS',
        description: 'صفحة ملف شخصي بسيطة تحتوي على معلومات أساسية.',
        requirements: ['اسم', 'نبذة', 'مهارات'],
        technologies: ['HTML', 'CSS'],
        steps: ['هيكل الصفحة', 'الطباعة', 'الهوامش', 'الألوان'],
        challenge: 'أضف قسم skills مع بطاقات.',
        bonus: 'أضف mode toggle محلي.',
        status: 'Not Started'
    },
    {
        id: 'landing-page',
        title: 'Simple Landing Page',
        difficulty: 'Beginner',
        language: 'HTML/CSS',
        description: 'صفحة هبوط لمنتج أو خدمة.',
        requirements: ['Hero', 'Features', 'Call to action'],
        technologies: ['HTML', 'CSS'],
        steps: ['إنشاء hero section', 'إضافة feature cards', 'تنسيق النص'],
        challenge: 'أضف navbar ومقطع pricing.',
        bonus: 'أضف responsive behavior.',
        status: 'Not Started'
    },
    {
        id: 'responsive-portfolio',
        title: 'Responsive Portfolio',
        difficulty: 'Intermediate',
        language: 'HTML/CSS',
        description: 'ملف شخصي متجاوب مع مشاريع وأقسام متعددة.',
        requirements: ['header', 'about', 'projects', 'contact'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['إنشاء الأقسام', 'CSS Grid/Flexbox', 'تعديل الهاتف'],
        challenge: 'أضف dark mode.',
        bonus: 'أضف scroll reveal.',
        status: 'Not Started'
    },
    {
        id: 'product-landing',
        title: 'Product Landing Page',
        difficulty: 'Intermediate',
        language: 'HTML/CSS',
        description: 'صفحة منتج كاملة للتسويق.',
        requirements: ['hero', 'features', 'pricing', 'testimonials'],
        technologies: ['HTML', 'CSS'],
        steps: ['إنشاء layout', 'تنسيق الأزرار', 'تنسيق pricing'],
        challenge: 'أضف تبديل بين خطتين للتسعير.',
        bonus: 'أضف animations للبطاقات.',
        status: 'Not Started'
    },
    {
        id: 'blog-ui',
        title: 'Blog UI',
        difficulty: 'Intermediate',
        language: 'HTML/CSS',
        description: 'واجهة تدوينات تشبه المدونة.',
        requirements: ['header', 'posts', 'sidebar', 'archive'],
        technologies: ['HTML', 'CSS'],
        steps: ['هيكلة الصفحة', 'تخطيط sidebar', 'تنسيق المقالات'],
        challenge: 'أضف قائمة تصنيفات وتغريدات.',
        bonus: 'أضف hover على بطاقات المقالات.',
        status: 'Not Started'
    },
    {
        id: 'ecommerce-frontend',
        title: 'E-commerce Front-End',
        difficulty: 'Advanced',
        language: 'HTML/CSS/JS',
        description: 'واجهة متجر إلكتروني بنظام بطاقات المنتجات وسلة.',
        requirements: ['header', 'products', 'cart', 'filter'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['تصميم الواجهة', 'إنشاء المنتجات', 'إضافة الكارت'],
        challenge: 'أضف فلترة المنتجات حسب الفئة.',
        bonus: 'اضبط السلة والحساب الإجمالي.',
        status: 'Not Started'
    },
    {
        id: 'admin-dashboard',
        title: 'Admin Dashboard',
        difficulty: 'Advanced',
        language: 'HTML/CSS/JS',
        description: 'لوحة تحكم لإدارة محتوى أو إحصائيات.',
        requirements: ['sidebar', 'cards', 'charts', 'table'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['إنشاء layout', 'إحصائيات', 'جدول البيانات'],
        challenge: 'بدّل البيانات ديناميكيًا عبر JavaScript.',
        bonus: 'أضف dark mode.',
        status: 'Not Started'
    },
    {
        id: 'advanced-portfolio',
        title: 'Advanced Portfolio',
        difficulty: 'Advanced',
        language: 'HTML/CSS/JS',
        description: 'بوابة شخصي احترافية مع sections متعددة وتحريك.',
        requirements: ['hero', 'work', 'about', 'contact'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['إضافة الإلكترونات', 'التبديل بين الأقسام', 'الرسوم المتحركة'],
        challenge: 'أضف شاشة البداية with typing effect.',
        bonus: 'أضف قوالب للمهارات والمشاريع.',
        status: 'Not Started'
    },
    {
        id: 'web-application',
        title: 'Web Application',
        difficulty: 'Expert',
        language: 'HTML/CSS/JS',
        description: 'تطبيق ويب كامل مع قوائم، تنقل، وتفاعل.',
        requirements: ['state', 'routing simulation', 'forms', 'cards'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['تخطيط الواجهة', 'إدارة الحالة', 'تفاعل المستخدم'],
        challenge: 'أضف ميزات حفظ البيانات محليًا.',
        bonus: 'أضف dashboard وتحليل حالة البيانات.',
        status: 'Not Started'
    },
    {
        id: 'developer-portfolio',
        title: 'Complete Developer Portfolio',
        difficulty: 'Expert',
        language: 'HTML/CSS/JS',
        description: 'ملف شخصي احترافي يضم السيرة، المشروع، المهارات، والتواصل.',
        requirements: ['header', 'about', 'projects', 'contact', 'resume'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['هيكلة البناء', 'العناصر التفاعلية', 'حفظ البيانات'],
        challenge: 'أضف sections للمهارات والخدمات.',
        bonus: 'أضف إشعارات لاستخدامات التفاعل.',
        status: 'Not Started'
    },
    {
        id: 'advanced-social-dashboard',
        title: 'Advanced Web App',
        difficulty: 'Expert',
        language: 'HTML/CSS/JS',
        description: 'لوحة تطبيقات متقدمة للعروض، الملاحظات، والتقارير.',
        requirements: ['sidebar', 'stats', 'cards', 'widgets'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['تصميم Layout', 'إحصائيات', 'تفاعل'],
        challenge: 'إضافة قائمة فرز وإظهار البيانات.',
        bonus: 'أضف themes and filters.',
        status: 'Not Started'
    },
    {
        id: 'todo-app',
        title: 'Daily Focus',
        difficulty: 'Intermediate',
        language: 'HTML/CSS/JavaScript',
        description: 'تطبيق مهام تفاعلي لإضافة المهام وإنجازها وحذفها.',
        requirements: ['إضافة المهام', 'تحديد المنجز', 'حذف المهام'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['بناء الواجهة', 'إدارة المهام', 'تحديث القائمة'],
        challenge: 'أضف حفظ المهام بعد تحديث الصفحة.',
        bonus: 'أضف مرشحات للمهام.',
        status: 'Not Started',
        demoType: 'todo'
    },
    {
        id: 'calculator-app',
        title: 'Pocket Calculator',
        difficulty: 'Beginner',
        language: 'HTML/CSS/JavaScript',
        description: 'آلة حاسبة تعمل بعمليات الجمع والطرح والضرب والقسمة.',
        requirements: ['لوحة أرقام', 'العمليات الأساسية', 'مسح القيمة'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['تصميم اللوحة', 'التقاط الأزرار', 'حساب النتائج'],
        challenge: 'أضف دعمًا للوحة المفاتيح.',
        bonus: 'أضف سجلًا للعمليات.',
        status: 'Not Started',
        demoType: 'calculator'
    },
    {
        id: 'ai-chat-ui',
        title: 'Prompt Studio',
        difficulty: 'Advanced',
        language: 'HTML/CSS/JavaScript',
        description: 'واجهة محادثة تفاعلية لعرض تجربة مساعد ذكي داخل المتصفح.',
        requirements: ['إرسال الرسائل', 'عرض المحادثة', 'حالات الواجهة'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['إنشاء المحادثة', 'إضافة حقل الإدخال', 'تحديث الرسائل'],
        challenge: 'اربط الواجهة بخدمة ذكاء اصطناعي عند توفر واجهة API.',
        bonus: 'أضف نسخ الرسائل.',
        status: 'Not Started',
        demoType: 'chat'
    },
    {
        id: 'weather-ui',
        title: 'Weather Window',
        difficulty: 'Intermediate',
        language: 'HTML/CSS/JavaScript',
        description: 'واجهة طقس تفاعلية تعرض حالات نموذجية بحسب المدينة المدخلة.',
        requirements: ['إدخال المدينة', 'عرض حالة الطقس', 'تحديث الواجهة'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['تصميم بطاقة الطقس', 'قراءة المدينة', 'عرض بيانات المعاينة'],
        challenge: 'اربط المشروع بمصدر بيانات طقس مباشر.',
        bonus: 'أضف توقعات الأيام القادمة.',
        status: 'Not Started',
        demoType: 'weather'
    },
    {
        id: 'programming-hub',
        title: 'Code Journal',
        difficulty: 'Advanced',
        language: 'HTML/CSS/JavaScript',
        description: 'واجهة لموقع برمجي مع مقالات وتصنيفات قابلة للتبديل.',
        requirements: ['مقالات', 'تصنيفات', 'تنقل تفاعلي'],
        technologies: ['HTML', 'CSS', 'JavaScript'],
        steps: ['بناء الصفحة', 'إضافة المقالات', 'تفعيل التصنيفات'],
        challenge: 'أضف بحثًا داخل المقالات.',
        bonus: 'أضف صفحة تفاصيل للمقال.',
        status: 'Not Started',
        demoType: 'blog'
    }
];

window.ALL_PROJECTS = window.PROJECTS_DATA;
